services:
  - type: web
    name: twitter-trends
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CHROME_BINARY_LOCATION
        value: "/usr/bin/google-chrome-stable"
    buildFilter:
      paths:
      - build.sh
      - requirements.txt