services:
  - type: web
    name: twitter-trends
    env: python
    region: oregon
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: |
      export PATH="${PATH}:/opt/render/project/.render/chrome/opt/google/chrome"
      export CHROME_PATH="/opt/render/project/.render/chrome/opt/google/chrome/google-chrome"
      export CHROMEDRIVER_PATH="/opt/render/project/src/.render/chromedriver"
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: RENDER
        value: "true"
      - key: CHROME_PATH
        value: "/opt/render/project/.render/chrome/opt/google/chrome/google-chrome"
      - key: CHROMEDRIVER_PATH
        value: "/opt/render/project/src/.render/chromedriver"